### ISSUE TITLE
Ransack 3.0.0

### ISSUE THREAD

**Issue by scarroll32** [activerecord-hackery/ransack#1210]
The next release of Ransack will be a major version bump: 3.0.0 🚀 

- With this release there will be a special announcement from @ernie, the creator of Ransack.

These issues and PRs are targeted for this release:

- [x] [Rename `master` to `main](https://github.com/activerecord-hackery/ransack/issues/1174) @scarroll32 
- [x] [Remove deprecated `#search` method ](https://github.com/activerecord-hackery/ransack/pull/1147)
- [x] [Merge Wiki and README into a GitHib Pages site](https://github.com/activerecord-hackery/ransack/issues/871) @scarroll32 
- [x] [Dropping support for 5.2](https://github.com/activerecord-hackery/ransack/pull/1276) @deivid-rodriguez 
- [ ] ~~[Update the Ransack Logo](https://github.com/activerecord-hackery/ransack/issues/1283)~~ @scarroll32 
- [x] [Allow scopes that define string SQL joins](https://github.com/activerecord-hackery/ransack/pull/1225) @mhssmnn - this just needs a note in the README

These can also be added if tests added / passing CI:

- [x] [Respect ransack_alias when sorting related tables](https://github.com/activerecord-hackery/ransack/pull/1084) @ekampp (released as 2.5.0, introduced by #1223)
- [ ] ~~[Added remove_association_no_negative_assoc to config to allow user to…](https://github.com/activerecord-hackery/ransack/pull/1123)~~ @Doctor06 
- [ ] ~~[Revert a change made in 2014 that prevent Ransack from finding the co](https://github.com/activerecord-hackery/ransack/pull/1051)~~ @scarroll32 
- [x] [Consider ransack aliases when sorting](https://github.com/activerecord-hackery/ransack/pull/766) @faragorn (released as 2.5.0, introduced by #1223)
- [x] [Evaluate ransackable_scopes before attributes](https://github.com/activerecord-hackery/ransack/pull/759) @faragorn
- [ ] ~~[Add the helper search_form_with](https://github.com/activerecord-hackery/ransack/issues/962)~~ @scarroll32 
- [x] [sort_link class: does not get passed correctly when no label argument passed (SortLink.new)](https://github.com/activerecord-hackery/ransack/issues/1277) @deivid-rodriguez

**Comment by seanfcarroll** [comment]
CC @y-yagi

**Comment by MatthewKennedy** [comment]
Adding the ability to search on Rails 7 encrypted columns `encrypts :email, deterministic: true`, would be pure genius and well 3.0 worthy.

**Comment by scarroll32** [comment]
We're going to release this soon - stay turned!

**Comment by deivid-rodriguez** [comment]
Two of the PRs in the second list have already been introduced, I marked them as complete! 🎉 

Also, the remaining items in the first list or "repository management tasks", so no really blockers for any release, no?

I plan to make this release the 24th of March.

**Comment by scarroll32** [comment]
> I plan to make this release the 24th of March.

@deivid-rodriguez this sounds like a great target date. Can we have a check-in around the 20th?

**Comment by scarroll32** [comment]
@deivid-rodriguez is there anything else you think we should add to 3.0.0?

**Comment by deivid-rodriguez** [comment]
No, not really, my plan is to simply release what's pending to be released (if there's anything) every two weeks. Hence the target date of two weeks from today, since I just released 2.6.0.

**Comment by scarroll32** [comment]
> No, not really, my plan is to simply release what's pending to be released (if there's anything) every two weeks. Hence the target date of two weeks from today, since I just released 2.6.0.

This is a great idea in general, and maybe we can event automate it. 

I'd like to make the 3.0.0 release special as it is the change to add any breaking changes as well as a major milestone, so maybe we will need a couple more days, but let's target the 24th.

**Comment by deivid-rodriguez** [comment]
Is there any pending breaking change that you want to make?

**Comment by scarroll32** [comment]
> Is there any pending breaking change that you want to make?

I believe [this](https://github.com/activerecord-hackery/ransack/pull/1147) is a breaking change. Not sure if there are any others.

**Comment by deivid-rodriguez** [comment]
Yes, that's the one we'll introduce for sure. Also the fix for #1277 apparently has the chance to break some usages so I will probably introduce that too.

**Comment by scarroll32** [comment]
> MatthewKennedy

Here's the tracking issue

**Comment by scarroll32** [comment]
3.0.0 [published on RubyGems](https://rubygems.org/gems/ransack).

Thanks for your help @deivid-rodriguez and [everyone who contributed](https://github.com/activerecord-hackery/ransack/blob/d428d7724b12f67e8b81836f73e8fcbd1a7ff05e/CHANGELOG.md) to this release. ☘️
