### ISSUE TITLE
2.3.1 todo list

### ISSUE THREAD

**Issue by gregmolnar** [activerecord-hackery/ransack#931]
- [ ] Add a generator to build in Ransack with a scaffold
- [ ] Generate tests for Ransack-enabled applications
- [ ] Update the Wiki / docs with lots of examples of 'how-to', questions are the majority of issues on Ransack
- [x] Increase supported translations

**Comment by seanfcarroll** [comment]
Closed
